// THIS FILE IS AUTO-GENERATED BY a script. DO NOT EDIT MANUALLY.

import type common from '@/locales/en/common.json';
import type { DotNestedKeys } from '@/types/utils';
import type { NAMESPACES } from './config';

// Define the master list of resources here.
export interface Resources {
  common: typeof common;
}

// Define the key-flattening logic here.
export type KeysForNamespace<N extends typeof NAMESPACES[number]> =
  N extends 'common'
    ? DotNestedKeys<Resources['common']>
    : never;
